### ISSUE TITLE
Please review my pull request

### ISSUE THREAD

**Issue by padaliyajay** [silverlogic/django-cloudflare-stream#3]
Hi friend 

I want to release my project tomorrow, it is dependent on my pull request otherwise i need to use fork. so can you please check and merge it

**Comment by nossila** [comment]
@padaliyajay I merged your pull request. We are also making this repository now read-only because all code has been [moved this other repo ](https://github.com/silverlogic/baseapp-backend/tree/master/baseapp-cloudflare-stream-field) where we have a proper workflow setup to release packages to pypi.

Could please re send your pull requests to that repo as well so we can release them on the pypi version?

https://pypi.org/project/baseapp-cloudflare-stream-field/

**Comment by padaliyajay** [comment]
Thank you for merged. i also created pull request in new repo
